version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - .docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/app
    ports:
      - 80:80
    links:
      - php
    networks:
      - backend
  php:
      build: .docker/php
      links:
        - db
      networks:
        - backend
      volumes:
        - .:/var/www/app
  db:
    container_name: mysql
    build: .docker/mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
    volumes:
      - .docker/mysql/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    networks:
        - backend
    command: 
      ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

networks:
    backend: